# Generated by Django 6.0.4 on 2026-04-08 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ahorro', 'Cuenta de Ahorro'), ('corriente', 'Cuenta Corriente')], default='ahorro', max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('retiro', 'Retiro'), ('transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='gestion.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='gestion.cuenta')),
            ],
        ),
    ]
